#include "KnowledgePackSelfTest.h"
#include "EffectKnowledgeBase.h"
#include "EffectKnowledgePack.h"
#include "EffectPresetId.h"
#include "ofFileUtils.h"
#include "ofJson.h"
#include "ofLog.h"
#include "ofUtils.h"
#include <cmath>

namespace videoeffects {

	namespace {

		int g_checks = 0;
		int g_failures = 0;

		void check(bool cond, const std::string & what) {
			g_checks++;
			if (!cond) {
				g_failures++;
				ofLogError("KnowledgePackSelfTest") << "FAIL: " << what;
			}
		}

		bool approxEqual(float a, float b, float eps = 1e-4f) { return std::fabs(a - b) < eps; }

	} // namespace

	bool runKnowledgePackRoundTripSelfTest(const std::vector<std::string> & knownEffectIds) {
		g_checks = 0;
		g_failures = 0;

		if (knownEffectIds.empty()) {
			ofLogWarning("KnowledgePackSelfTest") << "no known effect ids supplied — skipping self-test (nothing registered yet?)";
			return true; // not a failure of the pack code itself
		}
		const std::string realEffectId = knownEffectIds.front();
		const std::string fakeEffectId = "totally_fake_effect_id_zzz_not_registered";

		// Unique per process launch (this environment cannot rm -rf a
		// previous run's scratch files between runs, and shouldn't need to
		// -- the self-test must be safe to run repeatedly without ever
		// treating a PRIOR run's leftover files as this run's starting
		// state; EffectKnowledgeBase's own duplicate-detection would
		// otherwise make every "seed entry appended" check below flake on
		// a second launch that reuses the first launch's path).
		const std::string runId = ofToString(ofGetSystemTimeMillis());
		const std::string scratchRoot = "knowledge_roundtrip_selftest/run_" + runId;

		EffectKnowledgeBase sourceKb(scratchRoot + "/source");
		EffectKnowledgeBase targetKb(scratchRoot + "/target");
		const std::string packPath = scratchRoot + "/pack.json";

		// --- build source knowledge ------------------------------------
		KnowledgeEntry whiteEntry;
		whiteEntry.effect = realEffectId;
		whiteEntry.list = "whitelist";
		whiteEntry.snapshot["testParam"] = 0.42f;
		whiteEntry.tolerance["testParam"] = 0.1f;
		whiteEntry.label = "roundtrip-selftest-white";
		whiteEntry.notes = "generated by KnowledgePackSelfTest";
		whiteEntry.sourceSketch = "shader-effect-debugger-selftest";
		whiteEntry.sourceVideo = "none";
		whiteEntry.piSafe = true;
		whiteEntry.compatibleSceneIds = { "temporal-fields", "blueprint_emergence" };
		whiteEntry.presetId = synthesizeMigrationPresetId(realEffectId, "selftest_roundtrip");
		check(whiteEntry.presetId.has_value() && !whiteEntry.presetId->empty(), "synthesizeMigrationPresetId produced a non-empty id for the seed whitelist entry");
		check(sourceKb.appendWhitelist(whiteEntry), "seed whitelist entry appended to source KB");

		// DEC-016 effect-level default -- an independent record, not authored
		// on any one preset, verifying loadEffectLevelKnowledge/
		// saveEffectLevelKnowledge's own atomic-write round-trip and
		// exportEffectKnowledgePack's/importEffectKnowledgePack's new
		// effectDefaults array.
		EffectLevelKnowledge seedDefault;
		seedDefault.effectId = realEffectId;
		seedDefault.compatibleSceneIds = { "temporal-fields" };
		seedDefault.piSafe = true;
		check(sourceKb.saveEffectLevelKnowledge(seedDefault), "seed effect-level default saved to source KB");

		KnowledgeEntry blackEntry;
		blackEntry.effect = realEffectId;
		blackEntry.list = "blacklist";
		blackEntry.snapshot["testParam"] = 0.97f;
		blackEntry.forbiddenRanges["testParam"] = { 0.9f, 1.0f };
		blackEntry.label = "roundtrip-selftest-black";
		blackEntry.piSafe = false;
		// compatibleSceneIds deliberately left unset (nullopt) here, to
		// round-trip the "no override authored" case, not just the
		// populated one. The separate "explicit empty override" case
		// (present == true, vector empty -- "compatible with no scenes",
		// distinct from this "no override at all" case) is unit-tested at
		// the precedence layer in shared/src/video-effects/test/, not
		// re-verified here -- this self-test's job is I/O round-trip
		// fidelity, not precedence semantics.
		check(sourceKb.appendBlacklist(blackEntry), "seed blacklist entry appended to source KB");

		KnowledgeEntry unknownEntry;
		unknownEntry.effect = fakeEffectId;
		unknownEntry.list = "whitelist";
		unknownEntry.snapshot["x"] = 1.0f;
		check(sourceKb.appendWhitelist(unknownEntry), "seed unknown-effect entry appended to source KB");

		// --- export -------------------------------------------------------
		bool exportOk = exportEffectKnowledgePack(sourceKb, { realEffectId, fakeEffectId }, packPath, "shader-effect-debugger-selftest");
		check(exportOk, "exportEffectKnowledgePack succeeded");

		std::string resolvedPackPath = ofToDataPath(packPath, true);
		check(ofFile(resolvedPackPath).exists(), "exported pack file exists on disk");

		// --- import, with real known-id validation -------------------------
		EffectKnowledgePackImportReport report = importEffectKnowledgePack(packPath, targetKb, knownEffectIds);
		check(report.ok, "import reported ok");
		check(report.versionSupported, "import reported versionSupported");
		check(!report.schemaVersionWasAbsent, "exported pack's schemaVersion field was present (not absent)");
		check(report.schemaVersion == kEffectKnowledgePackCurrentSchemaVersion, "imported schemaVersion matches current constant");
		check(report.importedWhitelist == 1, "exactly one whitelist entry imported (real effect only)");
		check(report.importedBlacklist == 1, "exactly one blacklist entry imported");
		check(report.skippedUnknownEffect == 1, "the fake-effect-id entry was rejected, not silently imported");
		check(report.skippedMalformed == 0, "no entries were malformed");
		check(report.skippedInvalidPresetId == 0, "the seed entries' presetId was well-formed, nothing dropped");
		check(report.skippedDuplicatePresetId == 0, "only one presetId in this pack, nothing collided");
		check(report.importedEffectDefaults == 1, "the seed effect-level default was imported");

		// --- semantic round-trip verification ------------------------------
		auto whiteBack = targetKb.loadWhitelist(realEffectId);
		check(whiteBack.size() == 1, "target KB has exactly one whitelist entry for the real effect");
		if (!whiteBack.empty()) {
			const auto & e = whiteBack.front();
			check(e.effect == realEffectId, "round-tripped whitelist effect id matches");
			check(e.snapshot.count("testParam") == 1 && approxEqual(e.snapshot.at("testParam"), 0.42f), "round-tripped whitelist snapshot value matches");
			check(e.tolerance.count("testParam") == 1 && approxEqual(e.tolerance.at("testParam"), 0.1f), "round-tripped whitelist tolerance matches");
			check(e.piSafe.has_value() && *e.piSafe == true, "round-tripped whitelist piSafe == true (not lost, not defaulted)");
			check(e.compatibleSceneIds.has_value() && e.compatibleSceneIds->size() == 2, "round-tripped whitelist compatibleSceneIds count matches (override present)");
			check(e.list == "whitelist", "round-tripped entry's list field was normalized to whitelist");
			check(e.presetId.has_value() && e.presetId == whiteEntry.presetId, "round-tripped whitelist presetId matches the seeded value exactly");
			check(isReusableAuthoredPreset(e), "round-tripped whitelist entry is a reusable authored preset (well-formed, effect-matching presetId)");
		}

		auto defaultBack = targetKb.loadEffectLevelKnowledge(realEffectId);
		check(defaultBack.has_value(), "target KB has an effect-level default for the real effect after import");
		if (defaultBack.has_value()) {
			check(defaultBack->effectId == realEffectId, "round-tripped effect-level default effectId matches");
			check(defaultBack->compatibleSceneIds.size() == 1 && defaultBack->compatibleSceneIds.front() == "temporal-fields", "round-tripped effect-level default compatibleSceneIds matches");
			check(defaultBack->piSafe.has_value() && *defaultBack->piSafe == true, "round-tripped effect-level default piSafe matches");
		}

		auto blackBack = targetKb.loadBlacklist(realEffectId);
		check(blackBack.size() == 1, "target KB has exactly one blacklist entry for the real effect");
		if (!blackBack.empty()) {
			const auto & e = blackBack.front();
			check(e.piSafe.has_value() && *e.piSafe == false, "round-tripped blacklist piSafe == false (unsafe, not just absent)");
			check(!e.compatibleSceneIds.has_value(), "round-tripped blacklist compatibleSceneIds stayed absent (no override authored, distinguishable from an explicit empty override)");
			check(e.forbiddenRanges.count("testParam") == 1, "round-tripped blacklist forbiddenRanges present");
			if (e.forbiddenRanges.count("testParam") == 1) {
				check(approxEqual(e.forbiddenRanges.at("testParam").first, 0.9f), "round-tripped forbiddenRanges min matches");
				check(approxEqual(e.forbiddenRanges.at("testParam").second, 1.0f), "round-tripped forbiddenRanges max matches");
			}
		}

		// The fake-effect-id entry must NOT have reached the target KB at all.
		auto fakeBack = targetKb.loadWhitelist(fakeEffectId);
		check(fakeBack.empty(), "unknown-effect entry did not silently bind into the target KB under any id");

		// --- re-import is idempotent (duplicate-checked, not accumulating) --
		EffectKnowledgePackImportReport secondReport = importEffectKnowledgePack(packPath, targetKb, knownEffectIds);
		check(secondReport.ok, "second import still reports ok");
		check(secondReport.importedWhitelist == 0 && secondReport.importedBlacklist == 0, "second import added nothing new");
		check(secondReport.skippedDuplicate == 2, "second import recognized both entries as duplicates");
		auto whiteBackAgain = targetKb.loadWhitelist(realEffectId);
		check(whiteBackAgain.size() == 1, "re-importing the same pack did not duplicate the whitelist entry");

		// --- absent pack is not a failure -----------------------------------
		EffectKnowledgePackImportReport missingReport = importEffectKnowledgePack(scratchRoot + "/does_not_exist.json", targetKb, knownEffectIds);
		check(missingReport.ok, "importing a missing pack path reports ok (not a failure)");
		check(missingReport.importedWhitelist == 0 && missingReport.importedBlacklist == 0, "importing a missing pack imports nothing");

		// --- malformed pack (invalid JSON) fails deterministically ----------
		{
			std::string malformedPath = scratchRoot + "/malformed.json";
			ofFile malformedFile(ofToDataPath(malformedPath, true), ofFile::WriteOnly);
			malformedFile << "{ this is not valid json ";
			malformedFile.close();
			EffectKnowledgePackImportReport malformedReport = importEffectKnowledgePack(malformedPath, targetKb, knownEffectIds);
			check(!malformedReport.ok, "malformed-JSON pack is rejected (ok == false)");
			check(malformedReport.importedWhitelist == 0 && malformedReport.importedBlacklist == 0, "malformed-JSON pack imports nothing");
		}

		// --- pack with a partial/malformed entry (missing required field) ---
		{
			std::string partialPath = scratchRoot + "/partial.json";
			ofJson partialRoot;
			partialRoot["schemaVersion"] = 1;
			ofJson badEntry;
			badEntry["effect"] = realEffectId; // missing required "snapshot"
			partialRoot["whitelist"] = ofJson::array({ badEntry });
			partialRoot["blacklist"] = ofJson::array();
			ofSavePrettyJson(ofToDataPath(partialPath, true), partialRoot);
			EffectKnowledgeBase partialTargetKb(scratchRoot + "/partial_target");
			EffectKnowledgePackImportReport partialReport = importEffectKnowledgePack(partialPath, partialTargetKb, knownEffectIds);
			check(partialReport.ok, "a pack with one malformed entry still reports ok overall (entry-level skip, not whole-pack failure)");
			check(partialReport.skippedMalformed == 1, "the entry missing 'snapshot' was counted as skippedMalformed");
			check(partialReport.importedWhitelist == 0, "the malformed entry was not imported");
		}

		// --- invalid/duplicate presetId: entry survives, ID is dropped ------
		// DEC-016: "invalid or duplicate preset IDs must be rejected
		// deterministically" -- but per EffectKnowledgePack.h's own
		// contract this drops just the presetId field, not the whole
		// entry (an entry with a bad ID becomes a legacy-anonymous
		// preset, exactly like one that never had an ID at all).
		{
			std::string presetIdPath = scratchRoot + "/preset_id_edge_cases.json";
			ofJson root;
			root["schemaVersion"] = kEffectKnowledgePackCurrentSchemaVersion;

			ofJson invalidEntry;
			invalidEntry["effect"] = realEffectId;
			invalidEntry["snapshot"] = ofJson::object({ { "testParam", 0.10f } });
			invalidEntry["presetId"] = "preset.some_other_effect_entirely.slug"; // effect segment mismatch

			ofJson dupEntryA;
			dupEntryA["effect"] = realEffectId;
			dupEntryA["snapshot"] = ofJson::object({ { "testParam", 0.20f } });
			dupEntryA["presetId"] = "preset." + realEffectId + ".collides";

			ofJson dupEntryB;
			dupEntryB["effect"] = realEffectId;
			dupEntryB["snapshot"] = ofJson::object({ { "testParam", 0.30f } }); // different content -- not a content-duplicate
			dupEntryB["presetId"] = "preset." + realEffectId + ".collides"; // same id string as dupEntryA -- second occurrence loses the ID

			root["whitelist"] = ofJson::array({ invalidEntry, dupEntryA, dupEntryB });
			root["blacklist"] = ofJson::array();
			ofSavePrettyJson(ofToDataPath(presetIdPath, true), root);

			EffectKnowledgeBase presetIdTargetKb(scratchRoot + "/preset_id_target");
			EffectKnowledgePackImportReport presetIdReport = importEffectKnowledgePack(presetIdPath, presetIdTargetKb, knownEffectIds);
			check(presetIdReport.ok, "a pack with invalid/duplicate presetIds still reports ok overall (per-entry, not whole-pack)");
			check(presetIdReport.importedWhitelist == 3, "all three entries imported despite two having their presetId dropped");
			check(presetIdReport.skippedInvalidPresetId == 1, "the effect-mismatched presetId was counted as skippedInvalidPresetId");
			check(presetIdReport.skippedDuplicatePresetId == 1, "the second occurrence of the colliding presetId was counted as skippedDuplicatePresetId");

			auto imported = presetIdTargetKb.loadWhitelist(realEffectId);
			check(imported.size() == 3, "target KB received all three entries, not just the two with a valid unique id");
			int withPresetId = 0;
			int withoutPresetId = 0;
			for (const auto & e : imported) {
				if (e.presetId.has_value()) withPresetId++;
				else withoutPresetId++;
			}
			check(withPresetId == 1, "exactly one imported entry kept its presetId (the FIRST occurrence of the colliding id)");
			check(withoutPresetId == 2, "the effect-mismatched entry and the second colliding entry both fell back to legacy-anonymous");
		}

		// --- unsupported future schema version is rejected in full ----------
		{
			std::string futurePath = scratchRoot + "/future_version.json";
			ofJson futureRoot;
			futureRoot["schemaVersion"] = 999;
			ofJson futureEntry;
			futureEntry["effect"] = realEffectId;
			futureEntry["snapshot"] = ofJson::object({ { "testParam", 0.5f } });
			futureRoot["whitelist"] = ofJson::array({ futureEntry });
			futureRoot["blacklist"] = ofJson::array();
			ofSavePrettyJson(ofToDataPath(futurePath, true), futureRoot);
			EffectKnowledgeBase futureTargetKb(scratchRoot + "/future_target");
			EffectKnowledgePackImportReport futureReport = importEffectKnowledgePack(futurePath, futureTargetKb, knownEffectIds);
			check(!futureReport.ok, "schemaVersion 999 pack is rejected (ok == false)");
			check(!futureReport.versionSupported, "schemaVersion 999 pack reports versionSupported == false");
			check(futureReport.importedWhitelist == 0, "schemaVersion 999 pack imported nothing, even though its one entry was well-formed");
			auto shouldBeEmpty = futureTargetKb.loadWhitelist(realEffectId);
			check(shouldBeEmpty.empty(), "rejected-version pack left the target KB untouched");
		}

		bool allPassed = (g_failures == 0);
		ofLogNotice("KnowledgePackSelfTest") << (allPassed ? "PASS" : "FAIL") << ": " << (g_checks - g_failures) << "/" << g_checks << " checks passed";
		return allPassed;
	}

} // namespace videoeffects
